version: '3.7'
services:
  eureka-server: 
    build:
      context: ./server
      dockerfile: Dockerfile
    image: eureka-server
    ports:
      - "8081:8081"
    restart: always

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8081/eureka
      - spring.cloud.gateway.discovery.locator.enabled=true
      - spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true
    links:
      - eureka-server
    restart: always
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq  
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  
  db: 
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysqlpw
      MYSQL_ROOT_PASSWORD: mysqlpw
    ports:
      - "3307:3306"
    restart: always

  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    image: orders-ms
    environment:
      - spring.application.name=orders-ms
      - spring.datasource.url=jdbc:mysql://db:3306/vinissaumfood-orders?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=mysqlpw
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8081/eureka
      - eureka.instance.prefer-ip-address=true
    depends_on:
      - db
      - eureka-server
    links:
      - eureka-server
    ports:
      - "8083:8080"
    restart: always

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    image: payments-ms
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/vinissaumfood-payments?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=mysqlpw
    depends_on:
      - db
      - eureka-server
    links:
      - eureka-server
    restart: always
